### ISSUE TITLE
Clarifying normalization

### ISSUE THREAD

**Issue by jasnyder** [LRydin/KramersMoyal#10]
First, thank you so much for writing this package! Being able to quickly call a function to compute KM coefficients has been a considerable help in my current research.

I have a clarification to suggest in the main README.md regarding the normalization. Currently it is stated that one should multiply `kmc` by `delta_t` to obtain the actual Kramers-Moyal coefficients, but if I understand correctly one should in fact divide by `delta_t`.

**Comment by LRydin** [comment]
You are absolutely correct! You do indeed need to divide, not multiply. I will get that corrected right away before inducing someone else in error. Thanks!

**Comment by LRydin** [comment]
Thank you for the correction @jasnyder . I'd be happy for any other comments and remarks you might have on the package, as there are still a few things that could be improved :)
