### ISSUE TITLE
Bandwidth?

### ISSUE THREAD

**Issue by rodrigomp84** [LRydin/KramersMoyal#13]
Dear authors,

I'm sorry to pollute the github project, but can you comment a little bit on the bandwidth parameter? 
It's the only free parameter and it seems to have an important influence on the results, but it is not discussed in the docs nor on the paper.

Thank you for this great work,
best

**Comment by LRydin** [comment]
Hey @rodrigomp84, thanks for the question :).

Yeah, the bandwidth (`bw` in the code) is the only free parameter. It is comparable to a selection of bins in a histogram. In fact, this is something largely discussed in statistics, see e.g. [Kernel density estimation](https://en.wikipedia.org/wiki/Kernel_density_estimation) (kde). What is on the background of this is foregoing of classical disjoin bins, i.e., placing things in separate boxes, for a far smother version, using [kernels](https://en.wikipedia.org/wiki/Kernel_(statistics)#Nonparametric_statistics) (whichever type you prefer) and summing them up to get the final density function. This is called non-parametric estimation as it does not depent on the parameters of the model/process you are using.

If you check out `SciPy`'s [gaussian_kde](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html) you will also find it there, the `bw_method`. In there it points even to some particular methods for choosing the bandwidth size, i.e., Scott's or Silverman's. Naturally, `gaussian_kde` implies using a Gaussian kernel. `seaborn`'s [kdeplot](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) also uses kde with some bandwidth selection.

Now for the hard question: the choice of the bandwidth `bw`: This is the lifelong question of _how many bins are good for a histogram?_. Well, there you have [a few options](https://en.wikipedia.org/wiki/Histogram#Number_of_bins_and_width). Similarly, for kde you have some [rule-of-thumb](https://en.wikipedia.org/wiki/Kernel_density_estimation#A_rule-of-thumb_bandwidth_estimator).`kramersmoyal` implements the simple _Silverman's rule-of-thumb_ ¹ that relates the data's variance with the selection of the bandwidth `bw`. It is admittedly very simply, and it is one of the things I'd like to work on next, i.e., add other bandwidth selection methods (and something that at least tells the user which bandwidth was selected :) ).

Advantages over histograms: The paper [Kernel-based regression of drift and diffusion coefficients of stochastic processes](https://doi.org/10.1016/j.physleta.2009.07.073) discusses the advantages of kde over histograms for stochastic processes. It even proposes a new bandwidth selection method (which, again, I would like to implement as well... but I haven't :P )

Fell free to ask more if you need, I prefer these things be clear than somewhat hidden and unexplained. It is true I don't explain this neither in the docs nor in the paper, somewhat this is always relegated to "Statistician's problems, not mine", but I will definitely include some explanation in the docs in the following update.

¹ Silverman, B. W. _Density Estimation for Statistics and Data Analysis_. London: Chapman & Hall/CRC. p. 45. ISBN 978-0-412-24620-3 (1986)

**Comment by rodrigomp84** [comment]
Dear Leonardo,

this was extremely helpful, thank you very very much for the fast and detailed answer.
I should have gone through Kde before trying to use the code, I wasn't familiar with it. 
Now I have a more clear idea and know where to look. This Physics Letters paper is very helpful by the way, at least for a physicist like myself!

muito obrigado! :)
