### ISSUE TITLE
TypeError raised by test

### ISSUE THREAD

**Issue by Shibabrat** [LRydin/KramersMoyal#6]
I ran into the following error while executing one of the tests in test directory. Maybe I'm missing something and the authors can either fix or add instruction to specify usage. Other tests ran just fine.

>> run test/binning_test.py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Documents/review-JOSS/KramersMoyal/test/binning_test.py in <module>
     15
     16     hist1 = [np.histogramdd(timeseries, bins=bins,
---> 17                             weights=w, density=True)[0] for w in weights.T]
     18
     19     hist2 = histogramdd(timeseries, bins=bins,

~/Documents/review-JOSS/KramersMoyal/test/binning_test.py in <listcomp>(.0)
     15
     16     hist1 = [np.histogramdd(timeseries, bins=bins,
---> 17                             weights=w, density=True)[0] for w in weights.T]
     18
     19     hist2 = histogramdd(timeseries, bins=bins,

TypeError: histogramdd() got an unexpected keyword argument 'density'

**Comment by fmeirinhos** [comment]
Quite strange that you are getting that error since histogramdd has [density](https://github.com/LRydin/KramersMoyal/blob/master/kramersmoyal/binning.py#L29) as a keyword.

Is your repo matching the GitHub repository?

**Comment by Shibabrat** [comment]
@fmeirinhos perhaps my local repo was from the time of initial submission and the current version doesn't give me the error. Thanks. fixes #6

from kramersmoyal import km, kernels                                                                                                        

In [3]: run ./test/binning_test.py                                                                                                                  
Binning in 1D: passed
Binning in 2D: passed
Binning in 3D: passed
