### ISSUE TITLE
Community guidelines, code of conduct, issue and PR template

### ISSUE THREAD

**Issue by Shibabrat** [LRydin/KramersMoyal#7]
One of the JOSS requirements is to have community guidelines and code of conduct for interacting with the project. Authors can link pointers from the README to options under insights about:

Contribute to the software
Seek support for usage (authors have added this in README and can link it to the guidelines)
Report issues or PR (if the authors think users need to report in a specific style)

There are helpful templates created by GitHub to do these in Insights from the bar just under the repository name.

(Part of openjournals/joss-reviews#1693)

**Comment by LRydin** [comment]
Dear @Shibabrat and @kthyng,

I have added a Conduct of Fairness, plus a few lines on how to contact us. This includes the contributions.md file.
I've made the first steps in adding the ReadTheDocs (I'll add the content from the readme there and more extensive explanations on the binning and bandwidth).

Could you check if this is what is required? We don't have any specific "report issues" requirements, as in, a style or alike. If there are questions, we are happy to try to help and solve whatever is needed.

Refer: [openjournals/joss-reviews#1693](https://github.com/openjournals/joss-reviews/issues/1693)

Best,
Leonardo Rydin
@fmeirinhos

**Comment by kthyng** [comment]
@Shibabrat Can you check on what @LRydin has added?

**Comment by Shibabrat** [comment]
@kthyng looks good. I'm happy with this submission. 

@fmeirinhos Yes, the readthedocs style documentation is certainly a good way to add more helpful examples and to introduce the theory for beginners.
